name: Release

on:
  # We prefer manual release only
  workflow_dispatch:

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: yarn install

      - name: Build library
        run: yarn build

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          HUSKY: 0
