name: Test e2e

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  test-e2e:
    runs-on: ubuntu-20.04
    name: Test e2e
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Generate random paths
        run: |
          timestamp=$(date +%s)
          echo TEST_ID=$timestamp >> $GITHUB_OUTPUT
        id: random-path-generator
      - name: Install dependencies
        run: |
          yarn install
          npx playwright install
      - name: Run test
        run:  yarn test:e2e
        env:
          TEST_CLIENT_DOMAIN: ${{secrets.TEST_CLIENT_DOMAIN}}
          TEST_ID: ${{steps.random-path-generator.outputs.TEST_ID}}
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          status: ${{ job.status }}
          notification_title: "Segment E2E Test has {status_message}"
          # notify_when: "failure" # TODO: Activate this after test the bot itself
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}